# Generated by Django 2.2.6 on 2019-10-23 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojofarmville', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm', to='app_dojofarmville.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=300),
        ),
    ]
