# Generated by Django 2.2.6 on 2019-10-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojofarmville', '0003_auto_20191023_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='corn',
            name='identity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
