# Generated by Django 2.2.6 on 2019-10-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojofarmville', '0004_corn_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corn',
            name='identity',
        ),
    ]
