# Generated by Django 2.2.6 on 2019-10-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojofarmville', '0005_remove_corn_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corn',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corn', to='app_dojofarmville.Farm'),
        ),
        migrations.AlterField(
            model_name='corn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corn', to='app_dojofarmville.User'),
        ),
        migrations.CreateModel(
            name='Wheat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheat', to='app_dojofarmville.Farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheat', to='app_dojofarmville.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leek', to='app_dojofarmville.Farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leek', to='app_dojofarmville.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carrot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrot', to='app_dojofarmville.Farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrot', to='app_dojofarmville.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlackTomato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackTomato', to='app_dojofarmville.Farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackTomato', to='app_dojofarmville.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
