# Generated by Django 2.2.6 on 2019-10-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojofarmville', '0007_auto_20191023_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacktomato',
            name='isPicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blacktomato',
            name='isready',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrot',
            name='isPicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrot',
            name='isready',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corn',
            name='isPicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corn',
            name='isready',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leek',
            name='isPicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leek',
            name='isready',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wheat',
            name='isPicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wheat',
            name='isready',
            field=models.IntegerField(default=0),
        ),
    ]
