# Generated by Django 2.2.6 on 2019-10-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojofarmville', '0008_auto_20191023_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacktomato',
            name='isready',
        ),
        migrations.RemoveField(
            model_name='carrot',
            name='isready',
        ),
        migrations.RemoveField(
            model_name='corn',
            name='isready',
        ),
        migrations.RemoveField(
            model_name='leek',
            name='isready',
        ),
        migrations.RemoveField(
            model_name='wheat',
            name='isready',
        ),
        migrations.AddField(
            model_name='blacktomato',
            name='isReady',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrot',
            name='isReady',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corn',
            name='isReady',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leek',
            name='isReady',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wheat',
            name='isReady',
            field=models.IntegerField(default=0),
        ),
    ]
