# Generated by Django 2.2.6 on 2019-10-24 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojofarmville', '0009_auto_20191023_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacktomato',
            name='isPicked',
        ),
        migrations.RemoveField(
            model_name='blacktomato',
            name='isReady',
        ),
        migrations.RemoveField(
            model_name='carrot',
            name='isPicked',
        ),
        migrations.RemoveField(
            model_name='carrot',
            name='isReady',
        ),
        migrations.RemoveField(
            model_name='corn',
            name='isPicked',
        ),
        migrations.RemoveField(
            model_name='corn',
            name='isReady',
        ),
        migrations.RemoveField(
            model_name='leek',
            name='isPicked',
        ),
        migrations.RemoveField(
            model_name='leek',
            name='isReady',
        ),
        migrations.RemoveField(
            model_name='wheat',
            name='isPicked',
        ),
        migrations.RemoveField(
            model_name='wheat',
            name='isReady',
        ),
        migrations.CreateModel(
            name='WheatSeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheatSeed', to='app_dojofarmville.Farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheatSeed', to='app_dojofarmville.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeekSeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leekSeed', to='app_dojofarmville.Farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leekSeed', to='app_dojofarmville.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CornSeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cornSeed', to='app_dojofarmville.Farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cornSeed', to='app_dojofarmville.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlackTomatoSeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackTomatoSeed', to='app_dojofarmville.Farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackTomatoSeed', to='app_dojofarmville.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
