# Generated by Django 2.2.6 on 2019-10-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojofarmville', '0010_auto_20191024_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacktomatoseed',
            name='isReady',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cornseed',
            name='isReady',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leekseed',
            name='isReady',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wheatseed',
            name='isReady',
            field=models.IntegerField(default=0),
        ),
    ]
