# Generated by Django 2.2.6 on 2019-10-24 17:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojofarmville', '0012_carrotseed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='world',
            field=jsonfield.fields.JSONField(default=[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]),
        ),
    ]
