# Generated by Django 2.2.6 on 2019-10-24 18:47

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojofarmville', '0014_auto_20191024_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='world',
            field=jsonfield.fields.JSONField(default=[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]),
        ),
    ]
