# Generated by Django 2.2.6 on 2019-10-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojofarmville', '0017_auto_20191024_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacktomatoseed',
            name='isPlanted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrotseed',
            name='isPlanted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cornseed',
            name='isPlanted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leekseed',
            name='isPlanted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wheatseed',
            name='isPlanted',
            field=models.BooleanField(default=False),
        ),
    ]
