# Generated by Django 2.2.6 on 2019-10-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojofarmville', '0018_auto_20191025_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='world',
        ),
        migrations.AddField(
            model_name='event',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='starttime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='attender',
            field=models.ManyToManyField(null=True, related_name='plans', to='app_dojofarmville.User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='startdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_plans', to='app_dojofarmville.User'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm', to='app_dojofarmville.User'),
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('bPrice', models.IntegerField()),
                ('sPrice', models.IntegerField()),
                ('gRate', models.IntegerField()),
                ('output', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='app_dojofarmville.Farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='app_dojofarmville.User')),
            ],
        ),
    ]
